server:
  port: 38090
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog?autoReconnect=true&characterEncoding=utf8
    username: root
    password: 2636257370
  data:
    redis:
      host: localhost
      port: 6379
# 接口文档生成相关配置
springdoc:
  swagger-ui:
    path: /api.html
    tags-sorter: alpha
    operations-sorter: alpha
    # 是否启用swagger-ui
    enabled: true
  api-docs:
    path: /v1/api-docs
    # 是否启用api文档模板, 关闭后无法使用快速导入api文档
    enabled: true
logging:
  level:
    com.serliunx.blog: debug
# 通用配置
blog-common:
  # 是否输出业务异常信息
  output-service-exception: false