# 接口文档生成相关配置
springdoc:
  swagger-ui:
    path: /api.html
    tags-sorter: alpha
    operations-sorter: alpha
    # 是否启用swagger-ui
    enabled: false
  api-docs:
    path: /v1/api-docs
    # 是否启用api文档模板, 关闭后无法使用快速导入api文档
    enabled: false