server:
  servlet:
    context-path: /management-api
spring:
  application:
    name: management
  banner:
    location: other/Banner.txt
  profiles:
    active: local
  main:
    allow-circular-references: true
# 接口文档生成相关配置
springdoc:
  swagger-ui:
    path: /api.html
    tags-sorter: alpha
    operations-sorter: alpha
    # 是否启用swagger-ui
    enabled: false
  api-docs:
    path: /v1/api-docs
    # 是否启用api文档模板, 关闭后无法使用快速导入api文档
    enabled: false
# 日志
logging:
  level:
    root: info
# mybatis plus配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
# 安全模块通用配置信息
blog-security:
  # 是否启用身份认证过滤器
  enable-authentication-filter: true
  # 是否启用鉴权过滤器
  enable-common-permission-filter: true
# 通用配置
blog-common:
  # 是否输出业务异常信息
  output-service-exception: true
# 管理后台配置
management:
  # 用户相关
  user:
    # 用户名最大长度
    username-max-length: 32
    # 用户名最小长度
    username-min-length: 4
    # 密码最大长度
    password-max-length: 20
    # 密码最小长度
    password-min-length: 8