server:
  port: 38080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_blog?autoReconnect=true&characterEncoding=utf8
    username: root
    password: 2636257370
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    com.serliunx.blog: debug
# 管理后台配置
management:
  # 用户相关
  user:
    # 用户名最大长度
    username-max-length: 32
    # 用户名最小长度
    username-min-length: 4
    # 密码最大长度
    password-max-length: 20
    # 密码最小长度
    password-min-length: 8